// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersionAttribute("2.2.0")]
[assembly: AssemblyFileVersionAttribute("2.2.0")]
[assembly: AssemblyInformationalVersionAttribute("2.2.0 aca8a1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyVersion = "2.2.0";
        internal const System.String AssemblyFileVersion = "2.2.0";
        internal const System.String AssemblyInformationalVersion = "2.2.0 aca8a1";
    }
}
